# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: custom-backed-encrypter # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python2.7
  profile: firstwatch
  memorySize: 256
  region: us-east-1
  timeout: 180
  stage: dev

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "states:StartExecution"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ec2:StopInstances"
        - "ec2:StartInstances"
        - "ec2:CreateSnapshot"
        - "ec2:CreateVolume"
        - "ec2:Describe*"
        - "ec2:CopySnapshot"
        - "ec2:CreateTags"
        - "ec2:AttachVolume"
        - "ec2:DetachVolume"
        - "ec2:DeleteSnapshot"
        - "ec2:DeleteVolume"
        - "ec2:ModifyInstanceAttribute"
      Resource: "*"

functions:
  startstepfunctionencrypter:
    handler: startstepfunctionencrypter.run
    events:
      - sns: custom-backed-encrypter

  startsnapshot:
    handler: startssnapshot.run

  checksnapshot:
    handler: checksnapshot.run

  startcopy:
    handler: startcopy.run

  createvolume:
    handler: createvolume.run

  checkvolume:
    handler: checkvolume.run

  cleanup:
    handler: cleanup.run

resources:
  Resources:
    MyStateMachine:
      Type: AWS::StepFunctions::StateMachine
      Properties:
        StateMachineName: cbe-state-machine
        DefinitionString: |-
          {
            "Comment": "Custom Resource Encrypter State Machine.",
            "StartAt": "StartSnapshotTask",
            "States": {
              "StartSnapshotTask": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:us-east-1:955241386426:function:custom-backed-encrypter-dev-startsnapshot",
                "ResultPath": "$.volume_details",
                "Next": "CheckSnapshotTask"
              },
              "CheckSnapshotTask": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:us-east-1:955241386426:function:custom-backed-encrypter-dev-checksnapshot",
                "ResultPath": "$.snap_success",
                "Retry": [ {
                  "ErrorEquals": ["States.TaskFailed"],
                  "IntervalSeconds": 5,
                  "MaxAttempts": 3
                } ],
                "Next": "isSnapComplete"
              },
              "isSnapComplete": {
                "Type" : "Choice",
                "Choices": [
                  {
                    "Variable": "$.snap_success",
                    "StringEquals": "Complete",
                    "Next": "StartCopyTask"
                  }
                ],
                "Default": "PauseforCheck"
              },
              "PauseforCheck": {
                "Type": "Wait",
                "Seconds": 30,
                "Next": "CheckSnapshotTask"
              },
              "StartCopyTask": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:us-east-1:955241386426:function:custom-backed-encrypter-dev-startcopy",
                "ResultPath": "$.encrypted_snap_id",
                "Next": "CheckEncryptedSnapshotTask"
              },
              "CheckEncryptedSnapshotTask": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:us-east-1:955241386426:function:custom-backed-encrypter-dev-checksnapshot",
                "ResultPath": "$.snap_success",
                "Retry": [ {
                  "ErrorEquals": ["States.TaskFailed"],
                  "IntervalSeconds": 5,
                  "MaxAttempts": 3
                } ],
                "Next": "isEncryptedSnapComplete"
              },
              "isEncryptedSnapComplete": {
                "Type" : "Choice",
                "Choices": [
                  {
                    "Variable": "$.snap_success",
                    "StringEquals": "Complete",
                    "Next": "CreateVolumeTask"
                  }
                ],
                "Default": "PauseforEncryptedCheck"
              },
              "PauseforEncryptedCheck": {
                "Type": "Wait",
                "Seconds": 30,
                "Next": "CheckEncryptedSnapshotTask"
              },
              "CreateVolumeTask": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:us-east-1:955241386426:function:custom-backed-encrypter-dev-createvolume",
                "ResultPath": "$.encrypted_volume_id",
                "Next": "CheckVolumeTask"
              },
              "CheckVolumeTask": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:us-east-1:955241386426:function:custom-backed-encrypter-dev-checkvolume",
                "ResultPath": "$.volume_success",
                "Retry": [ {
                  "ErrorEquals": ["States.TaskFailed"],
                  "IntervalSeconds": 5,
                  "MaxAttempts": 3
                } ],
                "Next": "isVolumeReady"
              },
              "isVolumeReady": {
                "Type" : "Choice",
                "Choices": [
                  {
                    "Variable": "$.volume_success",
                    "StringEquals": "Complete",
                    "Next": "CleanupTask"
                  }
                ],
                "Default": "PauseforVolumeCheck"
              },
              "PauseforVolumeCheck": {
                "Type": "Wait",
                "Seconds": 30,
                "Next": "CheckVolumeTask"
              },
              "CleanupTask": {
                "Type": "Task",
                "Resource": "arn:aws:lambda:us-east-1:955241386426:function:custom-backed-encrypter-dev-cleanup",
                "ResultPath": "$.cleanup_success",
                "Next": "isCleanupComplete"
              },
              "isCleanupComplete": {
                "Type" : "Choice",
                "Choices": [
                  {
                    "Variable": "$.cleanup_success",
                    "StringEquals": "Complete",
                    "Next": "Finished"
                  }
                ],
                "Default": "CleanupFailed"
              },
              "CleanupFailed": {
                "Type": "Fail",
                "Cause": "Cleanup Failed.  Check CloudWatch Logs for more information."
              },
              "Finished": {
                "Type": "Succeed"
              }
            }
          }
        RoleArn: arn:aws:iam::111122223333:role/service-role/StatesExecutionRole-us-east-1